### ISSUE TITLE
Latest Bower version is not up to date

### ISSUE THREAD

**Issue by xremix** [JohnnyTheTank/bootstrap-block-grid#6]
When loading the latest bower version the `bower.json` file is not up to date.

The main property looks like the following:
`"main": "dist/bootstrap-block-grid.min.css",`
instead of 
`  "main": "dist/bootstrap3-block-grid.min.css",`
wich causes issues when running a task runner that is using the `main bower files`

**Comment by JohnnyTheTank** [comment]
fixed, thank you :)
