### ISSUE TITLE
Margins?

### ISSUE THREAD

**Issue by huphtur** [JohnnyTheTank/bootstrap-block-grid#8]
What's the best way to add some margins between the blocks without messing up the grid?

**Comment by JohnnyTheTank** [comment]
that's not the idea behind this concept

**Comment by JohnnyTheTank** [comment]
maybe you can fake margins with paddings

**Comment by JohnnyTheTank** [comment]
@huphtur: could you create a plnkr to demonstrate what you wanna do? you can fork this one: http://plnkr.co/qkyOlC

**Comment by huphtur** [comment]
I'm currently working with your precompiled block-grid and adding some margin (to create some room between the blocks) to [line 20](https://github.com/JohnnyTheTank/bootstrap-block-grid/blob/master/dist/bootstrap3-block-grid.css#L20) seems to mess up the grid.

**Comment by JohnnyTheTank** [comment]
thank you for this hint. I fixed it!
